### ISSUE TITLE
Add Mac/UNIX support

### ISSUE THREAD

**Issue by quietsamurai98** [quietsamurai98/BrainCubeInterpreter#2]
Currently, the `conio.h` header is used to get single characters from the console without requiring a newline. As `conio.h` is a non-standard header included with Windows, the whole program is incompatible with non-Windows operating systems.

Solution: Find a portable equivalent for the `getch()` command.

**Comment by quietsamurai98** [comment]
@Stenodyon, if I remember correctly, you forked the interpreter for MindMeld and added a Linux-compatible version of `getch()`. Would it be alright with you if I used your implementation of `getch()` in this project? I would give you attribution for the code that I end up using, of course.

**Comment by Stenodyon** [comment]
Sure! To be honest, I found most of the code [on StackOverflow](https://stackoverflow.com/questions/7469139/what-is-equivalent-to-getch-getche-in-linux) and cobbled it together, so you don't have to give attribution but that'd be fine by me.

**Comment by quietsamurai98** [comment]
Cool! At the very least, I'll leave a note in the comments of the source code.

**Comment by quietsamurai98** [comment]
Pushed commit adding Linux-compatible getch(). Closing issue, will make two more. One to test the Linux compatibility, one for Mac support.
